### ISSUE TITLE
Interaction in ipyleaflet maps stopped working in v0.4.0+

### ISSUE THREAD

**Issue by thohan88** [posit-dev/py-shinywidgets#174]
First of all, thanks for all the work on bringing ipywidgets to shiny, it is fantastic and much appreciated. 

**Description**:  
Since updating `shinywidgets` to v0.4.0, apps using `ipyleaflet` for interactive map updates (e.g., adding, updating, and removing markers) have stopped working. The app exits on update and the error message below is shown in the terminal.  This issue seems to be introduced in commit [72d16f5](https://github.com/posit-dev/py-shinywidgets/commit/72d16f570e3bc06529b2ac8cbae72bea193510b6). Installing from all previous commits (<=v0.3.4.9000) works perfectly.  

**Reproducible example:**
- [❌ with shinywidgets 0.4.2 (latest)](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMArhzxMAgugl04UQmQ4A3OAB0I9Rq07cA7hwAmAczhkWvfoOFyIhuHQD6Bk2YnERZVJ+dHTZDS1mDhwAG3kacOE+ASEmAFkoOgBrBwlE1A0NNFRHMSYAXlEOLChTRxoOUNCoACNwgAoPLx8Xfwa1MBg0ToBKXqy7OBpWB1U6Bq5vMndPaYkWOBYWDlJexA0mLaZmIoyGwkoKOgKGgFYATgwLs4AGACYLgEYJJ9uMAHYANjPfi96JAAvYiMApPe4DCDbHZJVJ0CxFEAAX0220IIjotjIjhYFFQhSYT1RW2JTHsI38jgEKyUpBYDVxcFQ61J0OpHFpEARTBArOh2yeiCYwA6tFCHGMbDIRPwTEu1y+r3e3wBTFFkQlUvunQk8puSs+Z16AF08Hz+Ux7kKRZ0NZLpTq5VcLj8Dd8jRJ1eL7drZXrfm7fqqvZqyABmR16xWE5UfE1mqEW-lh60h+0y3XOj5uuOe23eqURv3O10xz4-YP50MAFkjzrOgfj5v51dTVfTdeuHwbZY+3crYtDRczCrdXwHdqlteL12rPbenznJubKMTFrkZAxUPZnJYwEZqGNg2hAAE5AolKoMMMaHBFKTyaJUIYoBRHN0Ug56Sy1-yIKRQmIQgoFCJh0UxI4cTxZtwKxKCmQJJ5eBGWDIIPQoimrJg4FCRYwIxOD0IAakJZtmwAYiYABhUhxmEHdVihF8yCgJgyGIMkOEURikh4YgRhASdsSMIUGhqGYmEAiBelXJMmAYukCUpBSuQOAi0LxSE5KEqliBpRjuRAES1XEiQpN6JgaEEXhDDM18zNIXhtz0jkDNkpMKKYABVZ9XzgbCAA8OFxLhjCYKA7HCwxDCYCA4D0GFP3hZsrLoGzPVMyS1icyyC2xFSWAwDk4Bgb8Nl-OSOBGIwco-OEWHKuS5Lqr9gCMY0MEA4DOQJMT7Ky6Tm2hHDFkapqLRa+E2sMY0CUSJKxKA19GNOTLzK08b+RgDAoGihpJr3dqNotTyACUSuIVQmGIUIYoOlLrJqrhJOCsh9thL8MFSbBvx-TbkJs2LiGiKEdIKsb-q2ba5BgS64HepLDpm47IfsUCDumo8Ks25tz24q8uGUECjD8xxxIcBoIWPbYz0oewnDaMwH2GGFUAaP6kw3LcdkGHICWkNmcjycRRjocZejAJFjSAA)
- [✅ with shinywidgets 0.3.4 (latest working version)](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMArhzxMAgugl04UQmQ4A3OAB0I9Rq07cA7hwAmAczhkWvfoOFyIhuHQD6Bk2YnERZVJ+dHTZDS1mDhwAG3kacOE+ASEmAFkoOgBrBwlE1A0NNFRHMSYAXlEOLChTRxoOUNCoACNwgAoPLx8Xfwa1MBg0ToBKXqy7OBpWB1U6Bq5vMndPaYkWOBYWDlJexA0mLaZmIoyGwkoKOgKGgFYATgwLs4AGACYLgEYJJ9uMAHYANjPfi96JAAvYiMApPe4DCDbHZJVJ0CxFEAAX0220IIjotjIjhYFFQhSYT1RW2JTHsI38jgEKyUpBYDVxcFQ61J0OpHFpEARTBArOh2yeiCYwA6tFCHGMbDIRPwTEu1y+r3e3wBTFFkQlUvunQk8puSs+Z16AF08Hz+Ux7kKRZ0NZLpTq5VcLj8Dd8jRJ1eL7drZXrfm7fqqvZqyABmR16xWE5UfE1mqEW-lh60h+0y3XOj5uuOe23eqURv3O10xz4-YP50MAFkjzrOgfj5v51dTVfTdeuHwbZY+3crYtDRczCrdXwHdqlteL12rPbenznJubKMTFrkZAxUPZnJYwEZqGNg2hAAE5AolKoMMMaHBFKTyaJUIYoBRHN0Ug56Sy1-yIKRQmIQgoFCJh0UxI4cTxZtwKxKCmQJJ5eBGWDIIPQoimrJg4FCRYwIxOD0IAakJZtmwAYiYABhUhxmEHdVihF8yCgJgyGIMkOEURikh4YgRhASdsSMIUGhqGYmEAiBelXJMmAYukCUpBSuQOAi0LxSE5KEqliBpRjuRAES1XEiQpN6JgaEEXhDDM18zNIXhtz0jkDNkpMKKYABVZ9XzgbCAA8OFxLhjCYKA7HCwxDCYCA4D0GFP3hZsrLoGzPVMyS1icyyC2xFSWAwDk4Bgb8Nl-OSOBGIwco-OEWHKuS5Lqr9gCMY0MEA4DOQJMT7Ky6Tm2hHDFkapqLRa+E2sMY0CUSJKxKA19GNOTLzK08b+RgDAoGihpJr3dqNotTyACUSuIVQmGIUIYoOlLrJqrhJOCsh9thL8MFSbBvx-TbkJs2LiGiKEdIKsb-q2ba5BgS64HepLDpm47IfsUCDumo8Ks25tz24q8uGUECjD8xxxIcBoIWPbYz0oewnDaMwH2GGFUAaP6kw3LcdkGHICWkNmcjycRRjocZejAJE8HAaB4GoOQAEcxBho5CrIAKyHwIhSAoKhkHYLhsEZ8wCgKd4wwwatJeNIA)

**Local environment**:
- python: 3.11
- shiny: 1.2.1
- shinywidgets: 0.4.0+
- ipyleaflet: 0.19.1
- ipywidgets: 8.1.5

**Error message (shinylive):**
```
Traceback (most recent call last):
  File "/lib/python3.12/site-packages/shiny/reactive/_reactives.py", line 584, in _run
    await self._fn()
  File "/lib/python3.12/site-packages/shiny/_utils.py", line 279, in fn_async
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pyodide/app_kh331apovkrx44kaospm/app.py", line 36, in update_markers
    m.add(markers[id])
  File "/lib/python3.12/site-packages/ipyleaflet/leaflet.py", line 3150, in add
    self.layers = tuple([layer for layer in self.layers] + [item])
    ^^^^^^^^^^^
  File "/lib/python3.12/site-packages/traitlets/traitlets.py", line 716, in __set__
    self.set(obj, value)
  File "/lib/python3.12/site-packages/traitlets/traitlets.py", line 690, in set
    new_value = self._validate(obj, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/traitlets/traitlets.py", line 724, in _validate
    value = self._cross_validate(obj, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/traitlets/traitlets.py", line 730, in _cross_validate
    value = obj._trait_validators[self.name](obj, proposal)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/traitlets/traitlets.py", line 1241, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/ipyleaflet/leaflet.py", line 2971, in _validate_layers
    self._layer_ids = [layer.model_id for layer in proposal.value]
                       ^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/ipywidgets/widgets/widget.py", line 552, in model_id
    return self.comm.comm_id
           ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'comm_id'
/lib/python3.12/site-packages/shiny/reactive/_reactives.py:566: ReactiveWarning: Error in Effect: 'NoneType' object has no attribute 'comm_id'
  await self._run()
Unhandled error: 'NoneType' object has no attribute 'comm_id'
```

**Comment by davidwilby** [comment]
I'm also experiencing this and can confirm that things are working in 0.3.4.

**Comment by jmp75** [comment]
I've also bumped into this issue, trying to remove an ipyleaflet `GeoJSON` layer from a `Map`.  In case this helps, I have a side by side repro `jupyter-lab` versus `shiny` at [repro-ipyleaflet-removelayer](https://github.com/jmp75/repro-ipyleaflet-removelayer). 

```
shiny==1.2.1
shinywidgets==0.4.2
ipywidgets==7.8.5
ipyleaflet==0.19.2
jupyterlab==4.2.6
```
